### ISSUE TITLE
After update from 1.7.9 schedule error

### ISSUE THREAD

**Issue by bagyula** [xibosignage/xibo#2098]
Please help me:

I get the following error message wenn trying to set a schedule:

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'commandId' cannot be null#0 /var/www/cms/lib/Storage/PdoStorageService.php(205): PDOStatement->execute(Array) #1 /var/www/cms/lib/Entity/Schedule.php(719): Xibo\Storage\PdoStorageService->insert('\n INSE...', Array) #2 /var/www/cms/lib/Entity/Schedule.php(605): Xibo\Entity\Schedule->add() #3 /var/www/cms/lib/Controller/Schedule.php(932): Xibo\Entity\Schedule->save() #4 [internal function]: Xibo\Controller\Schedule->add() #5 /var/www/cms/vendor/akrabat/rka-slim-controller/RKA/Slim.php(79): call_user_func_array(Array, Array) #6 [internal function]: RKA\Slim->RKA\{closure}() #7 /var/www/cms/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array) #8 /var/www/cms/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch() #9 /var/www/cms/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call() #10 /var/www/cms/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call() #11 /var/www/cms/lib/Middleware/Actions.php(150): Slim\Middleware\MethodOverride->call() #12 /var/www/cms/lib/Middleware/Theme.php(36): Xibo\Middleware\Actions->call() #13 /var/www/cms/lib/Middleware/WebAuthentication.php(131): Xibo\Middleware\Theme->call() #14 /var/www/cms/lib/Middleware/CsrfGuard.php(63): Xibo\Middleware\WebAuthentication->call() #15 /var/www/cms/lib/Middleware/State.php(121): Xibo\Middleware\CsrfGuard->call() #16 /var/www/cms/lib/Middleware/Storage.php(48): Xibo\Middleware\State->call() #17 /var/www/cms/lib/Middleware/Xmr.php(37): Xibo\Middleware\Storage->call() #18 /var/www/cms/vendor/slim/slim/Slim/Slim.php(1300): Xibo\Middleware\Xmr->call() #19 /var/www/cms/web/index.php(127): Slim\Slim->run() #20 {main}
```

Thanks 
Gyula

**Comment by dasgarner** [comment]
Hi Gyula,

Please ask your question on the [Xibo Community](https://community.xibo.org.uk/c/support) and someone will try and help when they can. This tracker is for verified bugs only.

Thanks,
Dan
