### ISSUE TITLE
Editing a Repeating Event returns an unexpected error. 

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2203]
CMS Version: 2.3.3, custom install on Windows Server 2008 R2.

Issue: The User creates an Event that is set to repeat once daily. trying to Edit the Event returns an unexpected error.

Note: Troubleshot logs show the following exception:
```
An exception has been thrown during the rendering of a template (&quot;DateTime::__construct(): Failed to parse time string (2147483.647) at position 6 (3): Double time specification&quot;).#0 D:\cache\35\35a1f28ef80e07e3412608c451b8809f394053c2c819050403240eb15d8e9600.php(86): Twig\Template-&gt;displayBlock('formHtml', Array, Array)
#1 D:\removed\vendor\twig\twig\src\Template.php(216): __TwigTemplate_bb7bec71aabf73fa448344a97bcea66a7ae242a8911c1f039839017924e16662-&gt;block___internal_8c4df3e63e9b271e1ffa03d9848112476ad2df9cea21afef524ac0573ad8e215(Array, Array)
#2 D:\vendor\twig\twig\src\Template.php(286): Twig\Template-&gt;displayBlock('__internal_8c4d...', Array, Array, true)
#3 D:\cache\35\35a1f28ef80e07e3412608c451b8809f394053c2c819050403240eb15d8e9600.php(48): Twig\Template-&gt;renderBlock('__internal_8c4d...', Array, Array)
#4 D:\vendor\twig\twig\src\Template.php(455): __TwigTemplate_bb7bec71aabf73fa448344a97bcea66a7ae242a8911c1f039839017924e16662-&gt;doDisplay(Array, Array)
#5 D:\vendor\twig\twig\src\Template.php(422): Twig\Template-&gt;displayWithErrorHandling(Array, Array)
#6 D:\cache\cb\cb986cdeb9fe58d073f4f7c4ba81bfcbbd65fb24d7b04291508798fd63b7f9df.php(41): Twig\Template-&gt;display(Array, Array)
#7 D:\vendor\twig\twig\src\Template.php(455): __TwigTemplate_76758bf5f3292c3c2f6531fdc1d8e2e37d0c150185f7a6d703d101430425b6b8-&gt;doDisplay(Array, Array)
#8 D:\vendor\twig\twig\src\Template.php(422): Twig\Template-&gt;displayWithErrorHandling(Array, Array)
#9 D:\vendor\twig\twig\src\Template.php(434): Twig\Template-&gt;display(Array)
#10 D:\vendor\slim\views\Twig.php(91): Twig\Template-&gt;render(Array)
#11 D:\lib\Controller\Base.php(411): Slim\Views\Twig-&gt;render('schedule-form-e...', Array)
#12 D:\lib\Controller\Base.php(324): Xibo\Controller\Base-&gt;renderTwigAjaxReturn(Array, Object(RKA\Slim), Object(Xibo\Helper\ApplicationState))
#13 D:\lib\Middleware\State.php(117): Xibo\Controller\Base-&gt;render()
#14 [internal function]: Xibo\Middleware\State-&gt;Xibo\Middleware\{closure}()
#15 D:\vendor\slim\slim\Slim\Slim.php(1208): call_user_func_array(Object(Closure), Array)
#16 D:\vendor\slim\slim\Slim\Slim.php(1356): Slim\Slim-&gt;applyHook('slim.after.disp...')
#17 D:\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim-&gt;call()
#18 D:\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash-&gt;call()
#19 D:\lib\Middleware\Actions.php(150): Slim\Middleware\MethodOverride-&gt;call()
#20 D:\lib\Middleware\Theme.php(36): Xibo\Middleware\Actions-&gt;call()
#21 D:\lib\Middleware\WebAuthentication.php(131): Xibo\Middleware\Theme-&gt;call()
#22 D:\lib\Middleware\CsrfGuard.php(63): Xibo\Middleware\WebAuthentication-&gt;call()
#23 D:\lib\Middleware\State.php(121): Xibo\Middleware\CsrfGuard-&gt;call()
#24 D:\lib\Middleware\Storage.php(48): Xibo\Middleware\State-&gt;call()
#25 D:\lib\Middleware\Xmr.php(37): Xibo\Middleware\Storage-&gt;call()
#26 D:\vendor\slim\slim\Slim\Slim.php(1300): Xibo\Middleware\Xmr-&gt;call()
#27 D:\web\index.php(127): Slim\Slim-&gt;run()
#28 {main}
```
Also:
`An exception has been thrown during the rendering of a template (&quot;DateTime::__construct(): Failed to parse time string (2147483.647) at position 6 (3): Double time specification&quot;). Exception Type: Twig\Error\RuntimeError`

**Comment by dasgarner** [comment]
2147483647 (without the decimal point) is the DATE_MAX number which is used to represent always day parts in the schedule.

I can't recreate this problem on a normal install, and I can't see why the DATE_MAX would be used for a recurring event.
