### ISSUE TITLE
XiboClient has stopped working

### ISSUE THREAD

**Issue by solutionssquad** [xibosignage/xibo#401]
This may be similar to issue 282.
Running the latest Windows client on a Windows 8.1 machine, getting the following:

Faulting application name: XiboClient.exe, version: 2.0.0.0, time stamp: 0x54c69567
Faulting module name: KERNELBASE.dll, version: 6.3.9600.17278, time stamp: 0x53eeb4c3
Exception code: 0xe0434352
Fault offset: 0x0000f896
Faulting process id: 0xc5c
Faulting application start time: 0x01d0572308216597
Faulting application path: C:\Program Files\Xibo Player\XiboClient.exe
Faulting module path: C:\WINDOWS\system32\KERNELBASE.dll
Report Id: 2f54876a-c354-11e4-9745-00606ea5262f
Faulting package full name: 
Faulting package-relative application ID: 

Application: XiboClient.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
Stack:
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   at System.IO.StreamReader..ctor(System.String, System.Text.Encoding, Boolean, Int32, Boolean)
   at System.IO.StreamReader..ctor(System.String, System.Text.Encoding)
   at System.IO.File.InternalReadAllLines(System.String, System.Text.Encoding)
   at System.IO.File.ReadAllLines(System.String)
   at XiboClient.StatLog.ProcessQueueToXmds()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by dasgarner** [comment]
Please can you try this [latest development version](https://github.com/dasgarner/xibo-dotnetclient/blob/develop/bin/x86/Release/XiboClient.exe)?
